### ISSUE TITLE
Directivity balloon selection for sound source

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#53]
- The Directivity balloon' parameter of a sound source should not be enable (or visible) if 'Balloon' is not selected in the 'Directivity' parameter. 
- In addition, one can also remark that 'Directivity balloon' is displayed twice in the 'Directivity' parameter.

**Comment by nicolas-f** [comment]
Fixed

**Comment by Picaut** [comment]
Partially resolved (title of an directivity property element is not correct: See issue #147). Issue can be closed.
